src/Pages/Admin/Admin.cshtml.cs
using ContosoCrafts.WebSite.Models;
using ContosoCrafts.WebSite.Services;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace ContosoCrafts.WebSite.Pages
{
    /// <summary>
    /// Template for index (ie.Admin) page creation
    /// </summary>
    public class AdminModel : PageModel
    {
        //Logger
        private readonly ILogger<AdminModel> _logger;

        //Filter model to hold all criteria
        [BindProperty]
        public FilterModel Filter { get; set;}

        /// <summary>
        /// Constructor method for Admin Page
        /// </summary>
        /// <param name="logger"></param>
        /// <param name="productService"></param>
        public AdminModel(ILogger<AdminModel> logger, JsonFileProductService productService)
        {
            _logger = logger;
            ProductService = productService;
            Filter = new FilterModel();
        }

        // Declares a getter for ProductService
        public JsonFileProductService ProductService { get; }

        // Declares a public getter and a private setter for Products
        public IEnumerable<ProductModel> Products { get; private set; }

        /// <summary>
        /// Initializing method for Admin page. All products are shown.
        /// </summary>
        public void OnGet()
        {
            Products = ProductService.GetAllData();
        }

        /// <summary>
        /// Method to react to an action of clicking on the Create button
        /// on the Admin page. User gets redirected to Create page.
        /// </summary>
        /// <returns></returns>
        public IActionResult OnGetCreate()
        {
            return RedirectToPage("Create");
        }

        /// <summary>
        /// Method to react to action of submitting a filter via the Apply
        /// button. User gets the refreshed page with stated filters.
        /// </summary>
        /// <returns></returns>
        public IActionResult OnPost()
        {
            Products = ProductService.GetAllData();

            //Filter by Title
            if (Filter.Name != null)
            {
                var filterName = Filter.Name;
                Products = Products.Where(m => m.Title.ToLower().Contains(filterName.ToLower()));
            }

            //Filter by Region first, if chosen
            if (Filter.Region != null)
            {
                string val = Filter.Region;
                
                //Start with region
                Products = Products.Where(m => m.Region.Equals(val));
            }
            //Then filter by rating
            if (Filter.Rating != RatingEnums.ProductRating.UNKNOWN)
            {
                var rating = Filter.Rating;
                //Narrow down to rating
                Products = Products.Where(m => m.Rating.Equals(rating));
            }

            return Page();
        }

        /// <summary>
        /// Method to react to clicking of Clear button. Calls a clear data
        /// function in FilterModel to clear all filter data and reset the
        /// current selection of Products to be showing all Products
        /// </summary>
        /// <returns></returns>
        public IActionResult OnGetClear()
        {
            Filter.ClearData();
            Products = ProductService.GetAllData();

            return Page();
        }
    }
}

src/Pages/Admin/Create.cshtml.cs
using ContosoCrafts.WebSite.Models;
using ContosoCrafts.WebSite.Services;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Mvc;


namespace ContosoCrafts.WebSite.Pages
{
    /// <summary>
    /// The Create Model class provides the structure for how the Create
    /// page should behave.
    /// </summary>
    public class CreateModel : PageModel
    {
        // ILogger variable
        private readonly ILogger<CreateModel> _logger;

        /// <summary>
        /// Constructor method for the Create Page
        /// </summary>
        /// <param name="logger"></param>
        /// <param name="productService"></param>
        public CreateModel(ILogger<CreateModel> logger, JsonFileProductService productService)
        {
            _logger = logger;
            ProductService = productService;
        }

        //Product service object to provide all available services
        public JsonFileProductService ProductService { get; }

        // Getter and Setter method for the Creat page
        [BindProperty]
        public ProductModel Product { get; set; }

        /// <summary>
        /// Since we are creating a new record in the dataset, we don't need to pull anything for validation
        /// </summary>
        public void OnGet()
        {

        }

        /// <summary>
        /// Upon clicking Submit, the update is saved and the user is redirected back to the Admin page to 
        /// so they can update more information
        /// </summary>
        /// <returns></returns>
        public IActionResult OnPost()
        {
            //Check for input validation, if not valid, return to page
            if (ModelState.IsValid == false)
            {
                return Page();
            }

            //Check if input was just a bunch of numbers in Title
            if(hasLetters(Product.Title) == false)
            {
                ModelState.AddModelError(string.Empty, "Title must contain text.");
                return Page();
            }

            //Check if Description only has a bunch of numbers and symbols
            if(hasLetters(Product.Description) == false)
            {
                ModelState.AddModelError(string.Empty, "Description must contain text.");
                return Page();
            }

            //Check on url, whether the link leads to a valid image file
            if(validURL() == false)
            {
                ModelState.AddModelError(string.Empty, "Please enter an image url with the following extensions: .jpg, .jpeg, .png, .gif");
                return Page();
            }


            //If valid, create the card
            ProductService.CreateCard(Product);
            return RedirectToPage("Admin");
        }

        /// <summary>
        /// Function tests whether the input url directs to an actual image.
        /// Accepted image extensions are: jpg, jpeg, png and gif
        /// </summary>
        /// <returns></returns>
        private bool validURL()
        {
            string[] acceptedExtensions = { ".jpg", ".jpeg", ".png", ".gif" };
            foreach (string ext in acceptedExtensions) {
                if (Product.Image.Contains(ext))
                {
                    return true;
                }
            }
            
            return false;
        }

        /// <summary>
        /// Function tests whether the string t
        /// </summary>
        /// <returns></returns>
        private bool hasLetters(string strToCheck)
        {
            for (int i = 0; i < strToCheck.Length; i++)
            {
                if (char.IsLetter(strToCheck[i]))
                {
                    return true;
                }
            }

            return false;
        }
    }
}

src/Pages/Admin/Delete.cshtml.cs
using ContosoCrafts.WebSite.Models;
using ContosoCrafts.WebSite.Services;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace ContosoCrafts.WebSite.Pages
{
    /// <summary>
    /// Class for Delete page in CRUDi implementation
    /// </summary>
    public class DeleteModel : PageModel
    {
        //Variable to notify if an error has happened
        public bool errorOccurred = false;

        //Logger to help with debugging
        private readonly ILogger<DeleteModel> _logger;

        /// <summary>
        /// Constructor for Delete Page
        /// </summary>
        /// <param name="logger"></param>
        /// <param name="productService"></param>
        public DeleteModel(ILogger<DeleteModel> logger, JsonFileProductService productService)
        {
            _logger = logger;
            ProductService = productService;
        }

        //Product service object
        public JsonFileProductService ProductService { get; }

        //Product model object
        [BindProperty]
        public ProductModel Product { get; set; }

        /// <summary>
        /// Method for loading the requested item to get deleted
        /// </summary>
        /// <param name="id"></param>
        public void OnGet(string id)
        {
            Product = ProductService.GetAllData().FirstOrDefault(m => m.Id.Equals(id));

            //Flag if an error happened
            if (Product == null)
            {
                errorOccurred = true;
            }
        }

        /// <summary>
        /// Method for perform deletion and redirect the user back to Admin page
        /// </summary>
        /// <returns></returns>
        public IActionResult OnPost()
        {
            //delete card
            ProductService.DeleteCard(Product.Id);
            // Redirect back to the admin page to continue editing if needed
            return RedirectToPage("Admin");
        }
    }
}

src/Pages/Admin/Read.cshtml.cs
using System.Linq;
using ContosoCrafts.WebSite.Models;
using ContosoCrafts.WebSite.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace ContosoCrafts.WebSite.Pages
{
    /// <summary>
    /// Template for page creation
    /// </summary>
    public class ReadModel : PageModel
    {
        //Logger to help with debugging
        private readonly ILogger<ReadModel> _logger;

        //Product Service object used to access application's services
        public JsonFileProductService ProductService { get; }

        //Product object contains information about the product being shown
        public ProductModel Product { get; set; }

        //Variable to notify if an error has happened
        public bool errorOccurred = false;

        /// <summary>
        /// Constructor for Read Page
        /// </summary>
        /// <param name="logger"></param>
        /// <param name="productService"></param>

        public ReadModel(ILogger<ReadModel> logger, JsonFileProductService productService)
        {
            _logger = logger;
            ProductService = productService;
        }

        /// <summary>
        /// Method to load the selected item to be shown
        /// </summary>
        /// <param name="id"></param>
        public IActionResult OnGet(string id)
        {
            Product = ProductService.GetAllData().FirstOrDefault(m => m.Id.Equals(id));
            if (Product == null)
            {
                errorOccurred = true;
                //return RedirectToPage("./Admin");
            }

            return Page();
        }

        /// <summary>
        /// Method for redirecting users to Delete page when they choose to Delete
        /// the item.
        /// </summary>
        /// <param name="Id"></param>
        /// <returns></returns>
        public IActionResult OnGetDelete(string Id)
        {
            return RedirectToPage("Delete", new { id = Id });
        }

        /// <summary>
        /// Method for redirecting users to Update page when they choose to
        /// Update values in the item
        /// </summary>
        /// <param name="Id"></param>
        /// <returns></returns>
        public IActionResult OnGetUpdate(string Id)
        {
            return RedirectToPage("Update", new { id = Id });
        }
    }
}

src/Pages/Admin/Update.cshtml.cs
using ContosoCrafts.WebSite.Models;
using ContosoCrafts.WebSite.Services;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace ContosoCrafts.WebSite.Pages
{
    /// <summary>
    /// Template for page creation
    /// </summary>
    public class UpdateModel : PageModel
    {
        //Variable to notify if an error has happened
        public bool errorOccurred = false;

        /// <summary>
        /// Constructor for Update page
        /// </summary>
        /// <param name="productService"></param>
        public UpdateModel(JsonFileProductService productService)
        {
            ProductService = productService;
        }

        //Product service object
        public JsonFileProductService ProductService { get; }

        //Product model object
        [BindProperty]
        public ProductModel Product { get; set; }

        /// <summary>
        /// get the product details 
        /// </summary>
        /// <param name="id"></param>
        public void OnGet(string id)
        {
            Product = ProductService.GetAllData().FirstOrDefault(m => m.Id.Equals(id));

            //Flag if an error happened
            if (Product == null)
            {
                errorOccurred = true;
                //return RedirectToPage("./Admin");
            }
        }

        /// <summary>
        /// Post the model back to the page
        /// The model is in the class variable Product
        /// Call the data layer to Update that data
        /// Then return to the index page
        /// </summary>
        /// <returns></returns>
        public IActionResult OnPost()
        {
            //Check for input validation, if not valid, return to page
            if (ModelState.IsValid == false)
            {
                return Page();
            }

            //Check if input was just a bunch of numbers in Title
            if (hasLetters(Product.Title) == false)
            {
                ModelState.AddModelError("numbers", "Title must contain letters");
                return Page();
            }

            //Check if Description only has a bunch of numbers and symbols
            if (hasLetters(Product.Description) == false)
            {
                ModelState.AddModelError(string.Empty, "Description must contain text.");
                return Page();
            }

            ProductService.UpdateCard(Product);
            // Redirect back to the admin page to continue editing if needed
            return RedirectToPage("./Admin");
        }

        /// <summary>
        /// Function tests whether the string t
        /// </summary>
        /// <returns></returns>
        private bool hasLetters(string strToCheck)
        {
            for (int i = 0; i < strToCheck.Length; i++)
            {
                if (char.IsLetter(strToCheck[i]))
                {
                    return true;
                }
            }

            return false;
        }
    }
}

src/Pages/Admin/Admin.cshtml
@page
@using ContosoCrafts.WebSite.Components
@using ContosoCrafts.WebSite.Models
@using ContosoCrafts.WebSite.Services
@using Microsoft.AspNetCore.Components.Web
@using ContosoCrafts.WebSite.RatingEnums
@inject JsonFileProductService ProductService
@model AdminModel
@{
    ViewData["Title"] = "Admin";
    var regions = Model.ProductService.GetAllRegions();
    var fishRatings = Enum.GetValues(typeof(ProductRating));
}
<!--
This is the Index page where all records from the Seafoods.JSON file are display and
can be edited with CRUD implementation
-->
<link rel="stylesheet" href="~/css/site.css" type="text/css">

<head>
</head>
<body>
    <div class="container">
        <!--Table header and description-->
        <div class="text-body">
            <div class="d-flex flex-row justify-content-center align-items-center">
                <h2>Welcome to the Admin Page!</h2>
            </div>
            <div class="d-flex flex-row justify-content-center align-items-center">
                <p>Admins can manage the Seafood lists here. New records can be added, records can be updated or deleted<br /></p>
            </div>
        </div>
        <!--The Create button for adding a new record of Seafood-->
        <a class="btn btn-primary" asp-page-handler="Create"> Create</a>

        <form id="wow" method="post"></form>

        <!--Table to display all of the seafood records-->
        <table id="adminTable" class="table">
            <div class="row">
                <div class="col">
                    <input id="search" form="wow" type="text" asp-for="@Model.Filter.Name" placeholder="Find fish..." />
                    <button class="btn btn-success" form="wow" type="submit">Search</button>
                    <button class="btn btn-danger" form="wow" type="submit" onclick="$('#search').val('');$('#region').val('');$('#rating').val('@ProductRating.UNKNOWN')">Clear</button>
                </div>
            </div>
            <thead>
                <tr>
                    <th>Title</th>

                    <th>Source(s)</th>

                    <th>
                        <select id="region" class="custom-select" form="wow" asp-for="@Model.Filter.Region" onchange="this.form.submit()">
                            <option value="@null">Regions</option>
                            @{
                                foreach (string region in regions)
                                {
                                    <option value="@region">@region</option>
                                }
                            }
                        </select>
                    </th>
                    <th>
                        <select id="rating" class="custom-select" form="wow" asp-for="@Model.Filter.Rating" onchange="this.form.submit()">
                            <option value="@null">Ratings</option>
                            @{
                                var rating = Enum.GetValues(typeof(ProductRating));

                                foreach (int i in rating)
                                {
                                    // Do not show the Unknown rating on the form
                                    if (i == 0)
                                    {
                                        continue;
                                    }
                                    <option value="@i">@EnumExtensions.ConvertToString((ProductRating)i)</option>
                                }
                            }
                        </select>
                    </th>
                    <th>Decription</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var item in Model.Products)
                {
                <tr>
                    <!--<td>Html.DisplayFor(modelItem => item.Id)</td> - commenting out this code as we don't need to show users the ID-->
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>

                    <td>
                        @item.GetSources()
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Region)
                    </td>
                    <td>
                        @EnumExtensions.ConvertToString((item.Rating))
                    </td>
                    <td>
                        <div class="truncate">
                            @Html.DisplayFor(modelItem => item.Description)
                        </div>
                    </td>
                    <td>
                        <a class="btn btn-primary" asp-page="Read" asp-route-id="@(item.Id)">Edit</a>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</body>
<script src="_framework/blazor.server.js"></script>

@section scripts{
    <script>
        $(document).ready(function () {
            var adminTable = $('#adminTable').DataTable({
                ordering: false,
                searching: false,
                pagingType: "numbers",
                iDisplayLength: 15,
                bLengthChange: false,
            });
            $('.dataTables_length').addClass('bs-select');
        });
    </script>
}

src/Pages/Admin/Create.cshtml
@page
@using ContosoCrafts.WebSite.Components
@using ContosoCrafts.WebSite.Models;
@using ContosoCrafts.WebSite.RatingEnums
@model CreateModel

@{
    ViewData["Title"] = "Create";
}

@section scripts{
    <script>
        $(document).ready(function () {
            $('#btnAddSource').click(function (e) {
                var numOfSources = $("#sources").children().length;
                $("#sources").append(`<li><input class="form-control" name="Product.Sources[${numOfSources++}]" value=""/></li>`);
                document.getElementById("btnAddSource").hidden = (numOfSources >= 5) ? true : false;
                document.getElementById("btnRemoveSource").hidden = (numOfSources > 0) ? false : true;
            });
            $('#btnRemoveSource').click(function (e) {
                $('#sources').children().last().remove();
                var numOfSources = $("#sources").children().length;
                document.getElementById("btnAddSource").hidden = (numOfSources >= 5) ? true : false;
                document.getElementById("btnRemoveSource").hidden = (numOfSources > 0) ? false : true;
            });
        });
    </script>
}

<h1>Create a New Record</h1>

<!--This is the form for entering the data for a new Seafood Record. All fields are editable except for Product ID-->
@using (Html.BeginForm())
{
    <div asp-validation-summary="All"></div>

    

    <div class="form-group">
        <input hidden class="form-control" value="@System.Guid.NewGuid().ToString()" type="text" required asp-for="Product.Id">
    </div>

    <div class="form-group">
        <label>Title</label>
        <input class="form-control" type="text" required asp-for="Product.Title">
        <span asp-validation-for="Product.Title" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label>Region</label>
        <!-- Automatically parse from already available list of regions supported-->
        @{
            var temp = Model.ProductService.GetAllRegions();

            foreach (string region in temp)
            {
                <div class="form-check">
                    <input required asp-for="Product.Region" type="radio" value="@region">
                    <label class="form-check-label">
                        @region
                    </label>
                </div>
            }
        }
        <span asp-validation-for="Product.Region" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label>Fish Rating</label>
        @{
            var rating = Enum.GetValues(typeof(ProductRating));

            foreach (int i in rating)
            {
                // Do not show the Unknown rating on the form
                if (i == 0)
                {
                    continue;
                }
                <div class="form-check">
                    <input required asp-for="Product.Rating" type="radio" value="@i">
                    <label class="form-check-label" for="gridRadios1">
                        @EnumExtensions.ConvertToString((ProductRating)i)
                    </label>
                </div>
            }
        }
        <span asp-validation-for="Product.Rating" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label>Sources</label>
        <br />
        <ul id="sources">
            @if (Model.Product != null && Model.Product.Sources != null)
            {
                @for (var i = 0; i < Model.Product.Sources.Count; i++)
                {
                    <li><input class="form-control" type="text" name="Product.Sources[@i]" value="@Model.Product.Sources[i]"></li>
                }
            }
        </ul>
        <button id="btnAddSource" type="button" class="btn btn-secondary" style="">+ Add a source</button>
        <button id="btnRemoveSource" type="button" class='btn btn-danger' @((Model.Product != null && Model.Product.Sources != null)?"":"hidden")>- Remove source</button>
        <span asp-validation-for="Product.Sources" class="text-danger"></span>
    </div>
    <br />

    <div class="form-group">
        <label>Description</label>
        <input class="form-control" type="text" required asp-for="Product.Description">
        <span asp-validation-for="Product.Description" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label>Image (Accepted formats are: .jpg, .jpeg, .png, .gif)</label>
        <input class="form-control" type="url" pattern="https://.*" size="30" required asp-for="Product.Image" placeholder="https://example.com/fish-image.jpg"/>
        <span asp-validation-for="Product.Image" class="text-danger"></span>
    </div>

    <input class="btn btn-primary" type="submit" id="Submit">
}

src/Pages/Admin/Delete.cshtml
@page
@using ContosoCrafts.WebSite.Components
@model DeleteModel
@{
    ViewData["Title"] = "Delete";
}

<h1>Are you sure you want to delete this card?</h1>


<!-- Make sure the model is in valid state before we create anything. If error is null, then there's no error. Proceed.-->
@if (@Model.errorOccurred == true)
{
    <div>
        <h1> <b> Error: Item not found. <br>Click 'Okay' to get redirected back to Administrator page.</b> </h1>
        <a asp-page="./Admin" class="btn btn-primary"> Okay </a>
    </div>
}

@if (Model.errorOccurred == false)
{
    @using (Html.BeginForm(FormMethod.Post))
    {
        @Html.HiddenFor(m => m.Product.Id)

        <div class="form-group">
            <label>Title</label>
            <input class="form-control" type="text" asp-for="Product.Title" readonly>
        </div>

        <div class="form-group">
            <label>Region</label>
            <input class="form-control" type="text" asp-for="Product.Region" readonly>
        </div>

        <ul id="sources">
            @if (Model.Product.Sources != null && Model.Product.Sources.Count > 0)
            {
                @for (var i = 0; i < Model.Product.Sources.Count; i++)
                {
                    <li><input class="form-control" type="text" name="Product.Sources[@i]" value="@Model.Product.Sources[i]" readonly></li>
                }
            }
        </ul>

        <div class="form-group">
            <label>Rating</label>
            <input class="form-control" type="text" asp-for="Product.Rating" readonly>
        </div>

        <div class="form-group">
            <label>Description</label>
            <textarea class="form-control" asp-for="Product.Description" readonly></textarea>
        </div>

        <div class="form-group">
            <label>Image</label>
            <input class="form-control" type="text" asp-for="Product.Image" readonly>
        </div>

        <a class="btn btn-primary" asp-page="Read" asp-route-id="@(Model.Product.Id)">Cancel</a>
        <button type="submit" class="btn btn-danger">Delete</button>
    }
}

src/Pages/Admin/Read.cshtml
@page
@using ContosoCrafts.WebSite.Components
@model ReadModel
@{
    ViewData["Title"] = "Item";
}

<!--
    This is the read page to view the details of a selected record from the Admin page. Here the user will find an Update and Delete button
-->
<link rel="stylesheet" href="~/css/site.css" type="text/css">

<h1>Item Details</h1>

@if (@Model.errorOccurred == true)
{
    <div>
        <h1> <b> Error: Item not found. <br>Click 'Okay' to get redirected back to Administrator page.</b> </h1>
        <a asp-page="./Admin" class="btn btn-primary"> Okay </a>
    </div>
}

@if (Model.errorOccurred == false)
{
    @using (Html.BeginForm())
    {
        @Html.HiddenFor(m => m.Product.Id)

        <div class="form-group">
            <label>Title</label>
            <input class="form-control" type="text" asp-for="Product.Title" readonly>
        </div>

        <div class="form-group">
            <label>Region</label>
            <input class="form-control" type="text" asp-for="Product.Region" readonly>
        </div>

        <div class="form-group">
            @if (Model.Product.Sources != null && Model.Product.Sources.Count > 0)
            {
                <label>Sources</label>
                <ul>
                    @foreach (string source in Model.Product.Sources)
                    {
                        <li><input class="form-control" type="text" value="@source" readonly></li>
                    }
                </ul>
            }
        </div>

        <div class="form-group">
            <label>Rating</label>
            <input class="form-control" type="text" asp-for="Product.Rating" readonly>
        </div>

        <div class="form-group">
            <label>Description</label>
            <textarea class="form-control" asp-for="Product.Description" readonly></textarea>
        </div>

        <div class="form-group">
            <label>Image</label> <br>
            <!--<input class="form-control" type="text" asp-for="Product.Image" readonly> -->
            <div class="readwrapper">
                <img id="imgcontainer" src="@Model.Product.Image">
            </div>
        </div>

        <!-- User will be redirected to the Delete page to make confirm the delete action-->
        <a asp-page-handler="Delete" asp-route-id="@(Model.Product.Id)" class="btn btn-primary">Delete</a>

        <!-- User will be redirected to the Update page to make their edits and Save-->
        <a asp-page-handler="Update" asp-route-id="@(Model.Product.Id)" class="btn btn-primary">Update</a>
    }
}